FROM websphere-liberty:latest
MAINTAINER Erin Schnabel @ebullientworks

ENV LIBERTY_MODE run

ADD https://download.elastic.co/logstash-forwarder/binaries/logstash-forwarder_linux_amd64 /opt/forwarder
ADD ./servers/regroom /opt/ibm/wlp/usr/servers/defaultServer/

COPY ./forwarder.conf /opt/forwarder.conf
COPY ./startup.sh /opt/startup.sh

EXPOSE 9080

CMD ["/opt/startup.sh"]
